import { Topic } from '@/types'

export const keys = {
  article: (id: string) => `nid:article:${id}`,
  articlesByDate: () => 'nid:articles:by_date',
  articlesByRelevance: () => 'nid:articles:by_relevance',
  articlesBySentiment: () => 'nid:articles:by_sentiment',
  articlesByTopic: (topic: Topic) => `nid:articles:topic:${topic}`,
  articlesBySourceType: (type: string) => `nid:articles:source_type:${type}`,
  articlesBySource: (source: string) => `nid:articles:source:${source}`,
  articlesBySweep: (sweepId: string) => `nid:articles:sweep:${sweepId}`,
  articlesByCorroboration: (level: string) => `nid:articles:corr:${level}`,
  sweep: (id: string) => `nid:sweep:${id}`,
  sweepsByDate: () => 'nid:sweeps:by_date',
  entity: (name: string) => `nid:entity:${name}`,
  entitiesByMentions: () => 'nid:entities:by_mentions',
  entitiesByTrend: () => 'nid:entities:trend',
  entityArticles: (name: string) => `nid:entity:${name}:articles`,
  entitiesByTopic: (topic: Topic) => `nid:entities:topic:${topic}`,
  topicStats: (topic: Topic) => `nid:topic:stats:${topic}`,
  topicStatsUpdated: () => 'nid:topic:stats:updated',
  trendTopicDaily: (topic: Topic) => `nid:trend:topic:${topic}:daily`,
  trendSentimentDaily: () => 'nid:trend:sentiment:daily',
  trendSourcesDaily: () => 'nid:trend:sources:daily',
  trendEntitiesDaily: () => 'nid:trend:entities:daily',
  linkedin: (id: string) => `nid:linkedin:${id}`,
  linkedinByDate: () => 'nid:linkedin:by_date',
  linkedinBySweep: (sweepId: string) => `nid:linkedin:sweep:${sweepId}`,
  sourceQuality: (source: string) => `nid:source:quality:${source}`,
  sourcesByQuality: () => 'nid:sources:by_quality',
  marketdataEntity: (name: string) => `nid:marketdata:${name}`,
  marketdataByEntity: () => 'nid:marketdata:by_entity',
  marketdataSweep: (sweepId: string) => `nid:marketdata:sweep:${sweepId}`,
  marketdataMacro: () => 'nid:marketdata:macro',
}
